-- MySQL Script generated by MySQL Workbench
-- Thu Dec 14 22:16:55 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Membership`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Membership` (
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(1024) NOT NULL,
  `discount` DECIMAL NOT NULL,
  PRIMARY KEY (`title`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `second_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `membership_title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`, `email`, `membership_title`),
  INDEX `fk_User_Membership_idx` (`membership_title` ASC) VISIBLE,
  CONSTRAINT `fk_User_Membership`
    FOREIGN KEY (`membership_title`)
    REFERENCES `mydb`.`Membership` (`title`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Role` (
  `label` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`label`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `idEmployee` INT NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `second_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `INN` VARCHAR(45) NOT NULL,
  `SNILS` VARCHAR(45) NOT NULL,
  `role_label` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmployee`, `role_label`),
  INDEX `fk_Employee_Role1_idx` (`role_label` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_Role1`
    FOREIGN KEY (`role_label`)
    REFERENCES `mydb`.`Role` (`label`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contractor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contractor` (
  `idContractor` INT NOT NULL,
  `INN` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `company_name` VARCHAR(45) NOT NULL,
  `contact_number` VARCHAR(45) NULL,
  `contact_mail` VARCHAR(45) NULL,
  PRIMARY KEY (`idContractor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Delivery` (
  `idDelivery` INT NOT NULL,
  `delivery_cost` DECIMAL NOT NULL DEFAULT 0,
  `address` VARCHAR(1024) NULL,
  `contractor_id` INT NOT NULL,
  PRIMARY KEY (`idDelivery`, `contractor_id`),
  INDEX `fk_Delivery_Contractor1_idx` (`contractor_id` ASC) VISIBLE,
  CONSTRAINT `fk_Delivery_Contractor1`
    FOREIGN KEY (`contractor_id`)
    REFERENCES `mydb`.`Contractor` (`idContractor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sell`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sell` (
  `idSell` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `Employee_idEmployee` INT NOT NULL,
  `final_price` VARCHAR(45) NOT NULL,
  `sell_date` DATETIME NOT NULL,
  `discount` DECIMAL NOT NULL,
  `delivery_id` INT NULL,
  PRIMARY KEY (`idSell`, `Employee_idEmployee`),
  INDEX `fk_Sell_User1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_Sell_Employee1_idx` (`Employee_idEmployee` ASC) VISIBLE,
  INDEX `fk_Sell_Delivery1_idx` (`delivery_id` ASC) VISIBLE,
  CONSTRAINT `fk_Sell_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sell_Employee1`
    FOREIGN KEY (`Employee_idEmployee`)
    REFERENCES `mydb`.`Employee` (`idEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sell_Delivery1`
    FOREIGN KEY (`delivery_id`)
    REFERENCES `mydb`.`Delivery` (`idDelivery`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Documents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Documents` (
  `idDocuments` INT NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `contractor_id` INT NULL,
  PRIMARY KEY (`idDocuments`),
  INDEX `fk_Documents_Contractor1_idx` (`contractor_id` ASC) VISIBLE,
  CONSTRAINT `fk_Documents_Contractor1`
    FOREIGN KEY (`contractor_id`)
    REFERENCES `mydb`.`Contractor` (`idContractor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Shipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Shipment` (
  `idShipment` INT NOT NULL,
  `employee_id` INT NOT NULL,
  `contractor_id` INT NOT NULL,
  `document_id` INT NOT NULL,
  `delivery_date` DATETIME NULL,
  PRIMARY KEY (`idShipment`, `employee_id`, `contractor_id`, `document_id`),
  INDEX `fk_Shipment_Employee1_idx` (`employee_id` ASC) VISIBLE,
  INDEX `fk_Shipment_Contractor1_idx` (`contractor_id` ASC) VISIBLE,
  INDEX `fk_Shipment_Documents1_idx` (`document_id` ASC) VISIBLE,
  CONSTRAINT `fk_Shipment_Employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`Employee` (`idEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Shipment_Contractor1`
    FOREIGN KEY (`contractor_id`)
    REFERENCES `mydb`.`Contractor` (`idContractor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Shipment_Documents1`
    FOREIGN KEY (`document_id`)
    REFERENCES `mydb`.`Documents` (`idDocuments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ItemsInStock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ItemsInStock` (
  `idItemsInStock` INT NOT NULL,
  `label` VARCHAR(45) NOT NULL,
  `realization_date` DATE NOT NULL,
  `base_cost` DECIMAL NOT NULL,
  `balance` DECIMAL NOT NULL,
  `shipment_id` INT NOT NULL,
  PRIMARY KEY (`idItemsInStock`, `shipment_id`),
  INDEX `fk_ItemsInStock_Shipment1_idx` (`shipment_id` ASC) VISIBLE,
  CONSTRAINT `fk_ItemsInStock_Shipment1`
    FOREIGN KEY (`shipment_id`)
    REFERENCES `mydb`.`Shipment` (`idShipment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`File`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`File` (
  `idFiles` INT NOT NULL,
  `content` MEDIUMBLOB NOT NULL,
  `document_id` INT NOT NULL,
  PRIMARY KEY (`idFiles`, `document_id`),
  INDEX `fk_File_Documents1_idx` (`document_id` ASC) VISIBLE,
  CONSTRAINT `fk_File_Documents1`
    FOREIGN KEY (`document_id`)
    REFERENCES `mydb`.`Documents` (`idDocuments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sell_has_ItemsInStock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sell_has_ItemsInStock` (
  `sell_id` INT NOT NULL,
  `item_in_stock_id` INT NOT NULL,
  `amount` DECIMAL NOT NULL,
  `price` DECIMAL NOT NULL,
  PRIMARY KEY (`sell_id`, `item_in_stock_id`),
  INDEX `fk_Sell_has_ItemsInStock_ItemsInStock1_idx` (`item_in_stock_id` ASC) VISIBLE,
  INDEX `fk_Sell_has_ItemsInStock_Sell1_idx` (`sell_id` ASC) VISIBLE,
  CONSTRAINT `fk_Sell_has_ItemsInStock_Sell1`
    FOREIGN KEY (`sell_id`)
    REFERENCES `mydb`.`Sell` (`idSell`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sell_has_ItemsInStock_ItemsInStock1`
    FOREIGN KEY (`item_in_stock_id`)
    REFERENCES `mydb`.`ItemsInStock` (`idItemsInStock`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
