version: '3.1'

services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: maindb
      MYSQL_DATABASE: maindb
      MYSQL_USER: maindb
      MYSQL_PASSWORD: maindb
    volumes:
      - ./dbdata:/var/lib/mysq
