-- MySQL Script generated by MySQL Workbench
-- Tue Dec  5 21:15:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Role` (
  `id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USER` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `SecondName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NULL,
  `PhoneNumber` VARCHAR(45) NULL,
  `Role` INT NOT NULL,
  PRIMARY KEY (`id`, `Role`),
  INDEX `fk_USER_Role_idx` (`Role` ASC) VISIBLE,
  CONSTRAINT `fk_USER_Role`
    FOREIGN KEY (`Role`)
    REFERENCES `mydb`.`Role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contractors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contractors` (
  `idContractors` INT NOT NULL,
  `company_name` VARCHAR(45) NULL,
  `contact_number` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`idContractors`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Shipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Shipment` (
  `Id` INT NOT NULL,
  `DocumentNumber` VARCHAR(45) NULL,
  `Date` VARCHAR(45) NULL,
  `Contractors_idContractors` INT NOT NULL,
  PRIMARY KEY (`Id`, `Contractors_idContractors`),
  UNIQUE INDEX `DocumentNumber_UNIQUE` (`DocumentNumber` ASC) VISIBLE,
  INDEX `fk_Shipment_Contractors1_idx` (`Contractors_idContractors` ASC) VISIBLE,
  CONSTRAINT `fk_Shipment_Contractors1`
    FOREIGN KEY (`Contractors_idContractors`)
    REFERENCES `mydb`.`Contractors` (`idContractors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Delivery` (
  `id` INT NOT NULL,
  `Adress` VARCHAR(45) NULL,
  `DeliveryTime` VARCHAR(45) NULL,
  `Contractors_idContractors` INT NOT NULL,
  PRIMARY KEY (`id`, `Contractors_idContractors`),
  INDEX `fk_Delivery_Contractors1_idx` (`Contractors_idContractors` ASC) VISIBLE,
  CONSTRAINT `fk_Delivery_Contractors1`
    FOREIGN KEY (`Contractors_idContractors`)
    REFERENCES `mydb`.`Contractors` (`idContractors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SELL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SELL` (
  `Id` INT NOT NULL,
  `USER_id` INT NOT NULL,
  `Delivery_id` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `Discount` VARCHAR(45) NULL,
  `FinalPrice` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`, `Delivery_id`),
  INDEX `fk_SELL_USER1_idx` (`USER_id` ASC) VISIBLE,
  INDEX `fk_SELL_Delivery1_idx` (`Delivery_id` ASC) VISIBLE,
  CONSTRAINT `fk_SELL_USER1`
    FOREIGN KEY (`USER_id`)
    REFERENCES `mydb`.`USER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SELL_Delivery1`
    FOREIGN KEY (`Delivery_id`)
    REFERENCES `mydb`.`Delivery` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ItemsInStock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ItemsInStock` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `Shipment_Id` INT NOT NULL,
  `realization_date` DATE NULL,
  `ItemsInStockcol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `Shipment_Id`),
  INDEX `fk_ItemsInStock_Shipment1_idx` (`Shipment_Id` ASC) VISIBLE,
  CONSTRAINT `fk_ItemsInStock_Shipment1`
    FOREIGN KEY (`Shipment_Id`)
    REFERENCES `mydb`.`Shipment` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ItetmsInSell`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ItetmsInSell` (
  `Id` INT NOT NULL,
  `sell_Id` INT NOT NULL,
  `ItemsInStock_id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_ItetmsInSell_SELL1_idx` (`sell_Id` ASC) VISIBLE,
  INDEX `fk_ItetmsInSell_ItemsInStock1_idx` (`ItemsInStock_id` ASC) VISIBLE,
  CONSTRAINT `fk_ItetmsInSell_SELL1`
    FOREIGN KEY (`sell_Id`)
    REFERENCES `mydb`.`SELL` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ItetmsInSell_ItemsInStock1`
    FOREIGN KEY (`ItemsInStock_id`)
    REFERENCES `mydb`.`ItemsInStock` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
